title: Splashpage 002
author: Studiocraft
year: 2015

port: 3001
url: http://studiocraft.cc
baseurl: /002

exclude: [package.json, bower.json, Gruntfile.js, node_modules, bower_components, gulp, GitHub Repos, /**/styles, /**/scripts, .bowerrc, .sass-cache, .DS_Store, .gitignore, .editorconfig, .jshintrc, /*.yml, /*.txt, /*.md, /*.ai, /*.pdf, /*.indd, /*.idlk, /*.psd]
